@startuml
class App{
}

class Input{
+getProductName()
}

class Product{
-name: String
-price: String
-quantity: String
}

class JSONRecord{
-List: Product
+getProductRecord()
+openJSON()
+makeList()
+searchList()
+printSearchResults()
}

App o-- Input
App o-- JSONRecord
JSONRecord *-- Product

@enduml