@startuml
class Person{
- firstname : String
- lastname : String
+ getFirstname()
+ getLastname()
}

class Record{
- people : List
- recordCount : int
+ sortByAlpha()
+ addPeople()
+ getListofPeople()
+ getRecordCount()
+ printRecordToFile()
}

class App{
- fileName:String
}

class FileManager{
+findFile()
+readFile()
}

App o-- Record
Record *-- Person
App o-- FileManager
@enduml