@startuml
class App{
-fileName: String
}
class Record{
-people: List
-recordCount: int
+addPeople();
+printPeople();
}

class Person{
- firstName: String
- lastName: String
-salary: int
+ getFirstName()
+ getLastName()
+ getSalary()
}

class FileManager{
+ findFile()
+readFile()
}

App o-- FileManager
App o-- Record
Record o--Person
@enduml