@startuml
class App{
-fileName: String
}
class SalRecord{
-people: List
-recordCount: int
+addPeople();
+printPeople();
}

class Employee{
- firstName: String
- lastName: String
-salary: int
+ getFirstName()
+ getLastName()
+ getSalary()
}

class FileManager{
+ findFile()
+readFile()
}

App o-- FileManager
App o-- SalRecord
SalRecord o--Employee
@enduml