@startuml
class App{
}

class FileIn{
-fileData: ArrayList<String>
+getFilePath()
+importFile()
+getFileData()
}

class FrequencyFinder{
-wordMap: Map
+makeMap()
+getWordMap()
+sortbyValue()
+printHistogram()
}

App o-- FileIn
App o-- FrequencyFinder
@enduml